package com.nplus.physics.tiles

/** Port of AS3 tiletypes — all constants copied verbatim. */
object TileTypes {
    const val EMPTY         = 0
    const val FULL          = 1
    const val HALF_TOP      = 2
    const val HALF_RIGHT    = 3
    const val HALF_BOTTOM   = 4
    const val HALF_LEFT     = 5
    const val MED_PP        = 6
    const val MED_NP        = 7
    const val MED_NN        = 8
    const val MED_PN        = 9
    const val CONVEX_PP     = 10
    const val CONVEX_NP     = 11
    const val CONVEX_NN     = 12
    const val CONVEX_PN     = 13
    const val CONCAVE_PP    = 14
    const val CONCAVE_NP    = 15
    const val CONCAVE_NN    = 16
    const val CONCAVE_PN    = 17
    const val SMALL_22_PP   = 18
    const val SMALL_22_NP   = 19
    const val SMALL_22_NN   = 20
    const val SMALL_22_PN   = 21
    const val LARGE_22_PP   = 22
    const val LARGE_22_NP   = 23
    const val LARGE_22_NN   = 24
    const val LARGE_22_PN   = 25
    const val SMALL_67_PP   = 26
    const val SMALL_67_NP   = 27
    const val SMALL_67_NN   = 28
    const val SMALL_67_PN   = 29
    const val LARGE_67_PP   = 30
    const val LARGE_67_NP   = 31
    const val LARGE_67_NN   = 32
    const val LARGE_67_PN   = 33
    const val EDGE_TOP      = 34
    const val EDGE_RIGHT    = 35
    const val EDGE_BOTTOM   = 36
    const val EDGE_LEFT     = 37
    const val EDGE_CORNER_UL = 38
    const val EDGE_CORNER_UR = 39
    const val EDGE_CORNER_DL = 40
    const val EDGE_CORNER_DR = 41
    const val NUM_TILE_TYPES         = 42
    const val NUM_INGAME_TILE_TYPES  = 34

    /** Maps old (N v1 / N-game) type indices → new type constants. */
    val MAP_OLD_TO_NEW: IntArray = IntArray(NUM_INGAME_TILE_TYPES).also { m ->
        m[0]  = EMPTY;       m[1]  = FULL
        m[2]  = MED_PN;      m[3]  = MED_NN;      m[4]  = MED_NP;      m[5]  = MED_PP
        m[6]  = CONCAVE_PN;  m[7]  = CONCAVE_NN;  m[8]  = CONCAVE_NP;  m[9]  = CONCAVE_PP
        m[10] = CONVEX_PN;   m[11] = CONVEX_NN;   m[12] = CONVEX_NP;   m[13] = CONVEX_PP
        m[14] = SMALL_22_PN; m[15] = SMALL_22_NN; m[16] = SMALL_22_NP; m[17] = SMALL_22_PP
        m[18] = LARGE_22_PN; m[19] = LARGE_22_NN; m[20] = LARGE_22_NP; m[21] = LARGE_22_PP
        m[22] = SMALL_67_PN; m[23] = SMALL_67_NN; m[24] = SMALL_67_NP; m[25] = SMALL_67_PP
        m[26] = LARGE_67_PN; m[27] = LARGE_67_NN; m[28] = LARGE_67_NP; m[29] = LARGE_67_PP
        m[30] = HALF_BOTTOM; m[31] = HALF_RIGHT;  m[32] = HALF_TOP;    m[33] = HALF_LEFT
    }

    val XFORM_INVERT:  IntArray = IntArray(NUM_INGAME_TILE_TYPES)
    val XFORM_ROTCW:   IntArray = IntArray(NUM_INGAME_TILE_TYPES)
    val XFORM_ROTCCW:  IntArray = IntArray(NUM_INGAME_TILE_TYPES)
    val XFORM_FLIPH:   IntArray = IntArray(NUM_INGAME_TILE_TYPES)
    val XFORM_FLIPV:   IntArray = IntArray(NUM_INGAME_TILE_TYPES)

    init {
        XFORM_INVERT[EMPTY]=FULL; XFORM_INVERT[FULL]=EMPTY
        XFORM_INVERT[HALF_TOP]=HALF_BOTTOM; XFORM_INVERT[HALF_RIGHT]=HALF_LEFT
        XFORM_INVERT[HALF_BOTTOM]=HALF_TOP; XFORM_INVERT[HALF_LEFT]=HALF_RIGHT
        XFORM_INVERT[MED_PP]=MED_NN; XFORM_INVERT[MED_NP]=MED_PN
        XFORM_INVERT[MED_NN]=MED_PP; XFORM_INVERT[MED_PN]=MED_NP
        XFORM_INVERT[CONVEX_PP]=CONCAVE_NN; XFORM_INVERT[CONVEX_NP]=CONCAVE_PN
        XFORM_INVERT[CONVEX_NN]=CONCAVE_PP; XFORM_INVERT[CONVEX_PN]=CONCAVE_NP
        XFORM_INVERT[CONCAVE_PP]=CONVEX_NN; XFORM_INVERT[CONCAVE_NP]=CONVEX_PN
        XFORM_INVERT[CONCAVE_NN]=CONVEX_PP; XFORM_INVERT[CONCAVE_PN]=CONVEX_NP
        XFORM_INVERT[SMALL_22_PP]=LARGE_22_NN; XFORM_INVERT[SMALL_22_NP]=LARGE_22_PN
        XFORM_INVERT[SMALL_22_NN]=LARGE_22_PP; XFORM_INVERT[SMALL_22_PN]=LARGE_22_NP
        XFORM_INVERT[LARGE_22_PP]=SMALL_22_NN; XFORM_INVERT[LARGE_22_NP]=SMALL_22_PN
        XFORM_INVERT[LARGE_22_NN]=SMALL_22_PP; XFORM_INVERT[LARGE_22_PN]=SMALL_22_NP
        XFORM_INVERT[SMALL_67_PP]=LARGE_67_NN; XFORM_INVERT[SMALL_67_NP]=LARGE_67_PN
        XFORM_INVERT[SMALL_67_NN]=LARGE_67_PP; XFORM_INVERT[SMALL_67_PN]=LARGE_67_NP
        XFORM_INVERT[LARGE_67_PP]=SMALL_67_NN; XFORM_INVERT[LARGE_67_NP]=SMALL_67_PN
        XFORM_INVERT[LARGE_67_NN]=SMALL_67_PP; XFORM_INVERT[LARGE_67_PN]=SMALL_67_NP

        XFORM_ROTCW[EMPTY]=EMPTY; XFORM_ROTCW[FULL]=FULL
        XFORM_ROTCW[HALF_TOP]=HALF_RIGHT; XFORM_ROTCW[HALF_RIGHT]=HALF_BOTTOM
        XFORM_ROTCW[HALF_BOTTOM]=HALF_LEFT; XFORM_ROTCW[HALF_LEFT]=HALF_TOP
        XFORM_ROTCW[MED_PP]=MED_NP; XFORM_ROTCW[MED_NP]=MED_NN
        XFORM_ROTCW[MED_NN]=MED_PN; XFORM_ROTCW[MED_PN]=MED_PP
        XFORM_ROTCW[CONVEX_PP]=CONVEX_NP; XFORM_ROTCW[CONVEX_NP]=CONVEX_NN
        XFORM_ROTCW[CONVEX_NN]=CONVEX_PN; XFORM_ROTCW[CONVEX_PN]=CONVEX_PP
        XFORM_ROTCW[CONCAVE_PP]=CONCAVE_NP; XFORM_ROTCW[CONCAVE_NP]=CONCAVE_NN
        XFORM_ROTCW[CONCAVE_NN]=CONCAVE_PN; XFORM_ROTCW[CONCAVE_PN]=CONCAVE_PP
        XFORM_ROTCW[SMALL_22_PP]=SMALL_67_NP; XFORM_ROTCW[SMALL_22_NP]=SMALL_67_NN
        XFORM_ROTCW[SMALL_22_NN]=SMALL_67_PN; XFORM_ROTCW[SMALL_22_PN]=SMALL_67_PP
        XFORM_ROTCW[LARGE_22_PP]=LARGE_67_NP; XFORM_ROTCW[LARGE_22_NP]=LARGE_67_NN
        XFORM_ROTCW[LARGE_22_NN]=LARGE_67_PN; XFORM_ROTCW[LARGE_22_PN]=LARGE_67_PP
        XFORM_ROTCW[SMALL_67_PP]=SMALL_22_NP; XFORM_ROTCW[SMALL_67_NP]=SMALL_22_NN
        XFORM_ROTCW[SMALL_67_NN]=SMALL_22_PN; XFORM_ROTCW[SMALL_67_PN]=SMALL_22_PP
        XFORM_ROTCW[LARGE_67_PP]=LARGE_22_NP; XFORM_ROTCW[LARGE_67_NP]=LARGE_22_NN
        XFORM_ROTCW[LARGE_67_NN]=LARGE_22_PN; XFORM_ROTCW[LARGE_67_PN]=LARGE_22_PP

        XFORM_ROTCCW[EMPTY]=EMPTY; XFORM_ROTCCW[FULL]=FULL
        XFORM_ROTCCW[HALF_TOP]=HALF_LEFT; XFORM_ROTCCW[HALF_RIGHT]=HALF_TOP
        XFORM_ROTCCW[HALF_BOTTOM]=HALF_RIGHT; XFORM_ROTCCW[HALF_LEFT]=HALF_BOTTOM
        XFORM_ROTCCW[MED_PP]=MED_PN; XFORM_ROTCCW[MED_NP]=MED_PP
        XFORM_ROTCCW[MED_NN]=MED_NP; XFORM_ROTCCW[MED_PN]=MED_NN
        XFORM_ROTCCW[CONVEX_PP]=CONVEX_PN; XFORM_ROTCCW[CONVEX_NP]=CONVEX_PP
        XFORM_ROTCCW[CONVEX_NN]=CONVEX_NP; XFORM_ROTCCW[CONVEX_PN]=CONVEX_NN
        XFORM_ROTCCW[CONCAVE_PP]=CONCAVE_PN; XFORM_ROTCCW[CONCAVE_NP]=CONCAVE_PP
        XFORM_ROTCCW[CONCAVE_NN]=CONCAVE_NP; XFORM_ROTCCW[CONCAVE_PN]=CONCAVE_NN
        XFORM_ROTCCW[SMALL_22_PP]=SMALL_67_PN; XFORM_ROTCCW[SMALL_22_NP]=SMALL_67_PP
        XFORM_ROTCCW[SMALL_22_NN]=SMALL_67_NP; XFORM_ROTCCW[SMALL_22_PN]=SMALL_67_NN
        XFORM_ROTCCW[LARGE_22_PP]=LARGE_67_PN; XFORM_ROTCCW[LARGE_22_NP]=LARGE_67_PP
        XFORM_ROTCCW[LARGE_22_NN]=LARGE_67_NP; XFORM_ROTCCW[LARGE_22_PN]=LARGE_67_NN
        XFORM_ROTCCW[SMALL_67_PP]=SMALL_22_PN; XFORM_ROTCCW[SMALL_67_NP]=SMALL_22_PP
        XFORM_ROTCCW[SMALL_67_NN]=SMALL_22_NP; XFORM_ROTCCW[SMALL_67_PN]=SMALL_22_NN
        XFORM_ROTCCW[LARGE_67_PP]=LARGE_22_PN; XFORM_ROTCCW[LARGE_67_NP]=LARGE_22_PP
        XFORM_ROTCCW[LARGE_67_NN]=LARGE_22_NP; XFORM_ROTCCW[LARGE_67_PN]=LARGE_22_NN

        XFORM_FLIPH[EMPTY]=EMPTY; XFORM_FLIPH[FULL]=FULL
        XFORM_FLIPH[HALF_TOP]=HALF_TOP; XFORM_FLIPH[HALF_RIGHT]=HALF_LEFT
        XFORM_FLIPH[HALF_BOTTOM]=HALF_BOTTOM; XFORM_FLIPH[HALF_LEFT]=HALF_RIGHT
        XFORM_FLIPH[MED_PP]=MED_NP; XFORM_FLIPH[MED_NP]=MED_PP
        XFORM_FLIPH[MED_NN]=MED_PN; XFORM_FLIPH[MED_PN]=MED_NN
        XFORM_FLIPH[CONVEX_PP]=CONVEX_NP; XFORM_FLIPH[CONVEX_NP]=CONVEX_PP
        XFORM_FLIPH[CONVEX_NN]=CONVEX_PN; XFORM_FLIPH[CONVEX_PN]=CONVEX_NN
        XFORM_FLIPH[CONCAVE_PP]=CONCAVE_NP; XFORM_FLIPH[CONCAVE_NP]=CONCAVE_PP
        XFORM_FLIPH[CONCAVE_NN]=CONCAVE_PN; XFORM_FLIPH[CONCAVE_PN]=CONCAVE_NN
        XFORM_FLIPH[SMALL_22_PP]=SMALL_22_NP; XFORM_FLIPH[SMALL_22_NP]=SMALL_22_PP
        XFORM_FLIPH[SMALL_22_NN]=SMALL_22_PN; XFORM_FLIPH[SMALL_22_PN]=SMALL_22_NN
        XFORM_FLIPH[LARGE_22_PP]=LARGE_22_NP; XFORM_FLIPH[LARGE_22_NP]=LARGE_22_PP
        XFORM_FLIPH[LARGE_22_NN]=LARGE_22_PN; XFORM_FLIPH[LARGE_22_PN]=LARGE_22_NN
        XFORM_FLIPH[SMALL_67_PP]=SMALL_67_NP; XFORM_FLIPH[SMALL_67_NP]=SMALL_67_PP
        XFORM_FLIPH[SMALL_67_NN]=SMALL_67_PN; XFORM_FLIPH[SMALL_67_PN]=SMALL_67_NN
        XFORM_FLIPH[LARGE_67_PP]=LARGE_67_NP; XFORM_FLIPH[LARGE_67_NP]=LARGE_67_PP
        XFORM_FLIPH[LARGE_67_NN]=LARGE_67_PN; XFORM_FLIPH[LARGE_67_PN]=LARGE_67_NN

        XFORM_FLIPV[EMPTY]=EMPTY; XFORM_FLIPV[FULL]=FULL
        XFORM_FLIPV[HALF_TOP]=HALF_BOTTOM; XFORM_FLIPV[HALF_RIGHT]=HALF_RIGHT
        XFORM_FLIPV[HALF_BOTTOM]=HALF_TOP; XFORM_FLIPV[HALF_LEFT]=HALF_LEFT
        XFORM_FLIPV[MED_PP]=MED_PN; XFORM_FLIPV[MED_NP]=MED_NN
        XFORM_FLIPV[MED_NN]=MED_NP; XFORM_FLIPV[MED_PN]=MED_PP
        XFORM_FLIPV[CONVEX_PP]=CONVEX_PN; XFORM_FLIPV[CONVEX_NP]=CONVEX_NN
        XFORM_FLIPV[CONVEX_NN]=CONVEX_NP; XFORM_FLIPV[CONVEX_PN]=CONVEX_PP
        XFORM_FLIPV[CONCAVE_PP]=CONCAVE_PN; XFORM_FLIPV[CONCAVE_NP]=CONCAVE_NN
        XFORM_FLIPV[CONCAVE_NN]=CONCAVE_NP; XFORM_FLIPV[CONCAVE_PN]=CONCAVE_PP
        XFORM_FLIPV[SMALL_22_PP]=SMALL_22_PN; XFORM_FLIPV[SMALL_22_NP]=SMALL_22_NN
        XFORM_FLIPV[SMALL_22_NN]=SMALL_22_NP; XFORM_FLIPV[SMALL_22_PN]=SMALL_22_PP
        XFORM_FLIPV[LARGE_22_PP]=LARGE_22_PN; XFORM_FLIPV[LARGE_22_NP]=LARGE_22_NN
        XFORM_FLIPV[LARGE_22_NN]=LARGE_22_NP; XFORM_FLIPV[LARGE_22_PN]=LARGE_22_PP
        XFORM_FLIPV[SMALL_67_PP]=SMALL_67_PN; XFORM_FLIPV[SMALL_67_NP]=SMALL_67_NN
        XFORM_FLIPV[SMALL_67_NN]=SMALL_67_NP; XFORM_FLIPV[SMALL_67_PN]=SMALL_67_PP
        XFORM_FLIPV[LARGE_67_PP]=LARGE_67_PN; XFORM_FLIPV[LARGE_67_NP]=LARGE_67_NN
        XFORM_FLIPV[LARGE_67_NN]=LARGE_67_NP; XFORM_FLIPV[LARGE_67_PN]=LARGE_67_PP
    }

    fun getTypeFromChar(oldIndex: Int): Int = MAP_OLD_TO_NEW[oldIndex]
}
